Реализация компонента ввода UiInput
js-tasks-ru/vue-20211004_yus pull request #10
Opened 2021-11-11 08:53 UTC by yusforgithub

2021-11-11 08:54 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-11 08:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-11 09:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-11-14 06:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-14 10:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-11-15 15:06 UTC, ShGKme requested changes
В UiInput требуется добавить динамический компонент, остальные задачи приняты.

2021-11-16 05:24 UTC, yusforgithub commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +        },
Забыл про нереактивность слотов. Действительно. Перенесу в метод. Спасибо!

2021-11-16 05:25 UTC, yusforgithub commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +        />
Точно! Спасибо!

2021-11-16 12:45 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +        },
На самом деле эта проблема актуальна очень редко. Редко слоты появляются динамически. Здесь я "придираюсь", чтобы помнили о том, что $slots не реактивный объект :)

2021-11-17 09:14 UTC, yusforgithub commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +        },
Спасибо большое, что "придираетесь" - теперь надеюсь запомню про нереактивность слотов.

2021-11-17 09:15 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-17 09:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-03 10:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-01-07 08:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-08 09:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-01-08 09:42 UTC, ShGKme approved these changes
Все задачи приняты 👍

Были ли проблемы с `UiImageUploader`?

2022-01-08 09:42 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +    },
Лишнее свойство?

2022-01-08 09:43 UTC, merged