MeetupCover - фон css брать из параметра image
js-tasks-ru/vue-20211004_yus pull request #4
Opened 2021-10-17 18:50 UTC by yusforgithub

2021-10-17 21:36 UTC, ShGKme requested changes
Предлагается сделать решение, при котором не требуется добавлять новые классы, используя только вычисление CSS свойства с `v-bind`.

Для этого можно воспользоваться тернарным оператором и вывести или изображение по ссылке, или изображение по умолчанию. Это можно сделать прямо внутри `v-bind`, но лучше иметь как можно меньше сложных выражений как в шаблоне, так и в стилях, и вынести это вычисление в вычисляемое свойство компонента.

2021-10-17 21:36 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
>  }
Статическую часть стилей (независимую от данных) можно описывать статично, чтобы упрощать CSS и явно видеть, какая часть зависит от данных, а какая - нет.

```css
background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), v-bind('`url(${image})`');
```

2021-10-17 21:36 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
>  }
Сейчас добавление нового класса для разделения на случае "с изображением" и "без" усложнило решение по сравнению с этим же компонентом в прошлом модуле, а не упростило.

1. Добавился новый класс, который нужно устанавливать дополнительно, хотя `v-bind` должен был упростить шаблон, а не усложнять вёрстку
2. Пришлось дублировать код с градиентом затемнения. А это длинная строчка, где легко опечататься.

2021-10-18 13:55 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-10-18 14:32 UTC, merged